import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronRight } from "lucide-react";

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { DiscoveryCta } from "@/components/site-shell";
import { DashboardVisual, FieldVisual } from "@/components/platform-visuals";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Sentinel Vero — Operational control for fire & security contractors" },
    { name: "description", content: "Connect every enquiry, quote, job, site and payroll run in one operational system built for fire and security contractors." },
    { property: "og:title", content: "Sentinel Vero — See the leaks. Fix the system." },
    { property: "og:description", content: "Operational control for fire and security contractors who have outgrown fragmented systems." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ], links: [{ rel: "canonical", href: "/" }] }), component: HomePage,
});

const metrics: Array<[string, string, string]> = [['24','enquiries','waiting on you'],['18','quotes','sitting in limbo'],['56','jobs','running right now'],['342','sites',"someone’s responsible for"],['£126k','pipeline','still on the table'],['28','sites','overdue for service']];
const issues = [['The Stack','Timesheets in one app. Job tracking in another. Pricing living in someone’s head.'],['The Guess','Profit isn’t measured — it’s estimated, or patched together and hoped for.'],['The Headcount Fix','Compliance gets complicated, so the answer is always “hire another person”.']];
const chain = ['Customer','Quote','Job','Field','Review','Advisory','Invoice','Payroll'];
const promises = [['See','Every record, in context.'],['Verify','A trail you can trust, not a guess you hope is right.'],['Surface','The stuff that matters, first.'],['Improve','Decisions stay human. The system makes them easier to get right.']];
const features = ['CRM, customers, contacts & sites','Enquiries & opportunities','Job management & engineer workflows','Service & maintenance scheduling','Documents & compliance','Dashboards & reporting'];

function SectionHeading({ eyebrow, title, body }: { eyebrow: string; title: string; body?: string }) { return <div className="max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-4 text-balance font-display text-4xl font-semibold leading-tight md:text-5xl">{title}</h2>{body && <p className="mt-6 text-lg leading-8 text-muted-foreground">{body}</p>}</div>; }

function HomePage() {
  return <>
    <section className="hero-grid overflow-hidden bg-foreground text-background">
      <div className="site-container grid min-h-[calc(100svh-4.75rem)] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
        <div className="relative z-10"><p className="eyebrow text-primary">For fire & security contractors who are done guessing</p><h1 className="mt-5 max-w-3xl text-balance font-display text-5xl font-semibold leading-[0.98] md:text-7xl">You can’t measure what you can’t see.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-background/70">You know the leaks are there. You just can’t see them all at once. Sentinel Vero puts every enquiry, quote, job, site and payroll run in one place — with AI already working in the background — so you stop finding out too late.</p><Button asChild variant="signal" size="xl" className="mt-8"><a href="mailto:hello@sentinelvero.com?subject=Book%20a%20Discovery">Book a Discovery <ArrowRight /></a></Button><p className="mt-4 max-w-md text-xs leading-5 text-background/50">We don’t publish a price. Because we don’t sell software. We sell control.</p></div>
        <div className="relative"><DashboardVisual /></div>
      </div>
      <div className="border-t border-background/15"><div className="site-container grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6">{metrics.map(([number,label,note]) => <div key={number+label} className="border-b border-r border-background/15 p-5 lg:border-b-0"><strong className="font-mono text-2xl text-primary">{number}</strong><p className="mt-2 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-background/45">{note}</p></div>)}</div></div>
    </section>

    <section className="section-space"><div className="site-container"><SectionHeading eyebrow="The problem" title="Growth doesn’t break businesses. Spreadsheets do." body="Nobody plans to run a growing company like this. It happens one hire at a time, one workaround at a time — until the day nobody, including you, actually knows what’s going on. That’s not a technology problem. That’s a control problem."/><div className="mt-12 grid gap-3 md:grid-cols-3">{issues.map(([title,body],i) => <article key={title} className="issue-card"><span className="step-number">0{i+1}</span><h3>{title}.</h3><p>{body}</p></article>)}</div><div className="mt-16 grid gap-8 border-t border-border pt-10 sm:grid-cols-2 lg:grid-cols-4">{[['More people, more chaos.','Headcount goes up. So does the chasing.'],['Every quote is a guess.','Pricing lives in someone’s head, not in the system.'],['You find out last.','By the time you see the problem, it has already cost you money.'],['The business runs on memory.','Not process. And memory quits, gets sick, or leaves.']].map(([a,b]) => <div key={a}><h3 className="font-display text-lg font-bold">{a}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div></section>

    <section className="section-space bg-secondary"><div className="site-container"><SectionHeading eyebrow="The connected platform" title="One truth. Everywhere it’s needed." body="A customer becomes a quote. A quote becomes a job. A job becomes a payroll entry. Sentinel Vero makes it one thread, start to finish, so nothing gets lost between the field and the decision."/><div className="evidence-chain mt-12">{chain.map((item,i) => <div key={item} className="chain-item"><span>{String(i+1).padStart(2,'0')}</span><strong>{item}</strong>{i < chain.length-1 && <ChevronRight />}</div>)}</div><p className="mt-5 text-sm text-muted-foreground">Advisory auto-converts to quote. Payroll tracks every engineer.</p><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{['Customers, sites & assets','Enquiries & opportunities','Quotes & estimating','Jobs & engineer workflows','Service & maintenance','Documents & compliance','Dashboards & reporting','Automation & AI assistance'].map((item) => <div key={item} className="flex items-center gap-3 bg-background p-5 text-sm font-semibold"><Check className="size-4 text-primary"/>{item}</div>)}</div></div></section>

    <section className="section-space bg-foreground text-background"><div className="site-container"><SectionHeading eyebrow="Our position" title="We’re not another app on the pile." body="You don’t need one more login. You need someone who understands how fire and security businesses actually run — and builds the system around that, not the other way round."/><div className="mt-12 grid gap-px border border-background/15 bg-background/15 md:grid-cols-4">{promises.map(([title,body],i) => <article key={title} className="bg-foreground p-7"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-10 font-display text-2xl font-bold">{title}.</h3><p className="mt-3 text-sm leading-6 text-background/60">{body}</p></article>)}</div><p className="mt-8 text-xl font-semibold">Most platforms make you bend to fit them. <span className="text-primary">We bend to fit you.</span> That’s the whole difference.</p></div></section>

    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Who it’s for" title="Too big for spreadsheets. Too specific for generic software." body="Wherever you are in that growth, the story’s the same: things have gotten complicated, but you haven’t slowed down. Good — you shouldn’t have to."/><div className="divide-y divide-border border-y border-border">{[['10–20 people','You’re past DIY. Time to build the process before you hire your way out of the problem.'],['20–35 people','The workflows exist — they’re just not connected. Fix that before it costs you a client.'],['35–50 people','The business shouldn’t depend on the three people who remember everything. Build the reporting that lets you step back.']].map(([title,body]) => <div key={title} className="grid gap-3 py-6 sm:grid-cols-[9rem_1fr]"><h3 className="font-mono font-bold text-primary">{title}</h3><p className="text-muted-foreground">{body}</p></div>)}</div></div></section>

    <section className="section-space bg-secondary"><div className="site-container"><SectionHeading eyebrow="What’s included" title="Everything the job needs. Nothing you have to bolt on."/><div className="mt-12 grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div className="grid content-start gap-3">{features.map((item) => <div key={item} className="flex items-center gap-3 border-b border-border pb-3 text-sm font-semibold"><Check className="size-4 text-primary"/>{item}</div>)}</div><div className="grid gap-3 sm:grid-cols-2">{[['AI Quoting','The system knows the pricing logic, job history and site. Let it write the first draft.'],['AI Advisory','After a job wraps, likely next steps become a quote that’s ready to send.'],['Time Tracking & Payroll','Engineers log time as they work. It flows straight into payroll.'],['Automatic Mileage','Nobody logs it by hand. Nobody checks it by hand either.'],['Field App','Capture evidence, update the job and log time while it’s happening.']].map(([title,body],i) => <article key={title} className={i===0 ? 'feature-card sm:col-span-2' : 'feature-card'}><span className="status-pill">Included</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></div></section>

    <section className="section-space"><div className="site-container"><SectionHeading eyebrow="The platform" title="Office control. Field clarity." body="A single operational thread, shown differently to the people who need to act on it."/><div className="mt-12 grid items-center gap-10 lg:grid-cols-[1fr_auto]"><DashboardVisual/><FieldVisual/></div><div className="mt-8"><Button asChild variant="outline" size="lg"><Link to="/platform">See how to use the platform <ArrowRight /></Link></Button></div></div></section>

    <section className="section-space bg-foreground text-background"><div className="site-container grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="eyebrow text-primary">Proof</p><h2 className="mt-4 max-w-3xl font-display text-4xl font-semibold">We build this inside a real business, not a slide deck.</h2><p className="mt-4 text-background/60">Real client results, not slides.</p></div><Button asChild variant="inverse" size="lg"><Link to="/proof">View proof <ArrowRight /></Link></Button></div></section>

    <section className="section-space"><div className="site-container"><SectionHeading eyebrow="How it works" title="We look before we build."/><div className="mt-12 grid gap-px overflow-hidden rounded-md border border-border bg-border md:grid-cols-5">{[['Discover','We learn how you actually work.'],['Configure','The platform bends to fit.'],['Migrate','Your records, moved properly.'],['Launch','Trained, tested, live.'],['Improve','We keep tuning it.']].map(([title,body],i) => <div key={title} className="bg-background p-6"><span className="step-number">0{i+1}</span><h3 className="mt-8 font-display text-lg font-bold">{title}.</h3><p className="mt-2 text-sm text-muted-foreground">{body}</p></div>)}</div></div></section>

    <section className="section-space bg-secondary"><div className="site-container grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><SectionHeading eyebrow="Partnership & pricing" title="Simple enough to say yes to. Structured enough to trust." body="Sentinel Vero is licensed per user, with pricing shaped by your team size, migration needs and the workflows you configure. You’ll get a clear quote after an Operational Discovery, not a generic tier."/><div className="space-y-3">{[['A 12-month partnership','Not a subscription you forget you’re paying for.'],['Implementation & migration, scoped to you','Not a flat fee that ignores how messy your data actually is.'],['Room to grow','Add what you need later — properly scoped, not bolted on.']].map(([title,body]) => <div key={title} className="border-l-2 border-primary bg-background p-5"><h3 className="font-display font-bold">{title}.</h3><p className="mt-2 text-sm text-muted-foreground">{body}</p></div>)}</div></div></section>

    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><SectionHeading eyebrow="FAQ" title="Straight answers."/><Accordion type="single" collapsible className="border-t border-border">{[['How long does this take?','Depends on your data and your team. You’ll get a real timeline on the Discovery call — not a guess now.'],['What does it run on?','Browser, for the office. A dedicated app, for the field. Apple and Android.'],['How is this different from generic job software?','It’s built around how fire and security businesses actually quote, schedule and prove compliance.'],['We already pay for Simpro, Uptick or Out On Site — why bother?','Because paying for software and using it properly are two different things. If you’re still running half your workflow through spreadsheets, that’s the gap we close.'],['How does pricing actually work?','Per user, plus a one-off setup and migration fee. Real numbers come after a Discovery call — because your business isn’t generic, and neither is your quote.']].map(([q,a],i) => <AccordionItem value={`item-${i}`} key={q}><AccordionTrigger className="py-6 text-left text-base">{q}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <DiscoveryCta />
  </>;
}