/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CustomBuildRouteImport } from './routes/custom-build'
import { Route as LeakReport2026RouteImport } from './routes/leak-report-2026'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ProofIndexRouteImport } from './routes/proof.index'
import { Route as ProofSlugRouteImport } from './routes/proof.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildRoute = CustomBuildRouteImport.update({
  id: '/custom-build',
  path: '/custom-build',
  getParentRoute: () => rootRouteImport,
} as any)
const LeakReport2026Route = LeakReport2026RouteImport.update({
  id: '/leak-report-2026',
  path: '/leak-report-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofIndexRoute = ProofIndexRouteImport.update({
  id: '/proof/',
  path: '/proof/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofSlugRoute = ProofSlugRouteImport.update({
  id: '/proof/$slug',
  path: '/proof/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/leak-report-2026': typeof LeakReport2026Route
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/proof/': typeof ProofIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/leak-report-2026': typeof LeakReport2026Route
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/proof': typeof ProofIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/leak-report-2026': typeof LeakReport2026Route
  '/platform': typeof PlatformRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/proof/': typeof ProofIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/custom-build'
    | '/leak-report-2026'
    | '/platform'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/proof/$slug'
    | '/blog/'
    | '/guides/'
    | '/proof/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/custom-build'
    | '/leak-report-2026'
    | '/platform'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/proof/$slug'
    | '/blog'
    | '/guides'
    | '/proof'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/custom-build'
    | '/leak-report-2026'
    | '/platform'
    | '/security'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/proof/$slug'
    | '/blog/'
    | '/guides/'
    | '/proof/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomBuildRoute: typeof CustomBuildRoute
  LeakReport2026Route: typeof LeakReport2026Route
  PlatformRoute: typeof PlatformRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ProofSlugRoute: typeof ProofSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProofIndexRoute: typeof ProofIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-build': {
      id: '/custom-build'
      path: '/custom-build'
      fullPath: '/custom-build'
      preLoaderRoute: typeof CustomBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leak-report-2026': {
      id: '/leak-report-2026'
      path: '/leak-report-2026'
      fullPath: '/leak-report-2026'
      preLoaderRoute: typeof LeakReport2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/': {
      id: '/proof/'
      path: '/proof'
      fullPath: '/proof/'
      preLoaderRoute: typeof ProofIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$slug': {
      id: '/proof/$slug'
      path: '/proof/$slug'
      fullPath: '/proof/$slug'
      preLoaderRoute: typeof ProofSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomBuildRoute: CustomBuildRoute,
  LeakReport2026Route: LeakReport2026Route,
  PlatformRoute: PlatformRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ProofSlugRoute: ProofSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProofIndexRoute: ProofIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
