/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CustomBuildRouteImport } from './routes/custom-build'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ProofIndexRouteImport } from './routes/proof.index'
import { Route as ProofSlugRouteImport } from './routes/proof.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBuildRoute = CustomBuildRouteImport.update({
  id: '/custom-build',
  path: '/custom-build',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofIndexRoute = ProofIndexRouteImport.update({
  id: '/proof/',
  path: '/proof/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofSlugRoute = ProofSlugRouteImport.update({
  id: '/proof/$slug',
  path: '/proof/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/platform': typeof PlatformRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/proof/': typeof ProofIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/platform': typeof PlatformRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/proof': typeof ProofIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/custom-build': typeof CustomBuildRoute
  '/platform': typeof PlatformRoute
  '/proof/$slug': typeof ProofSlugRoute
  '/proof/': typeof ProofIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/custom-build' | '/platform' | '/proof/$slug' | '/proof/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/custom-build' | '/platform' | '/proof/$slug' | '/proof'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/custom-build'
    | '/platform'
    | '/proof/$slug'
    | '/proof/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CustomBuildRoute: typeof CustomBuildRoute
  PlatformRoute: typeof PlatformRoute
  ProofSlugRoute: typeof ProofSlugRoute
  ProofIndexRoute: typeof ProofIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-build': {
      id: '/custom-build'
      path: '/custom-build'
      fullPath: '/custom-build'
      preLoaderRoute: typeof CustomBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/': {
      id: '/proof/'
      path: '/proof'
      fullPath: '/proof/'
      preLoaderRoute: typeof ProofIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$slug': {
      id: '/proof/$slug'
      path: '/proof/$slug'
      fullPath: '/proof/$slug'
      preLoaderRoute: typeof ProofSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CustomBuildRoute: CustomBuildRoute,
  PlatformRoute: PlatformRoute,
  ProofSlugRoute: ProofSlugRoute,
  ProofIndexRoute: ProofIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
